spring.application.name=picpay-challenge
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/picpay_challenge_db
spring.datasource.hikari.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

jwt-secret-key=G5jU$1vM#p!sX2W@zQ9oT7cY&rB3dK8fL6N^aC0E*JmP4Vx%hF#yMZqWj^8d@

spring.cloud.aws.credentials.accessKey=key
spring.cloud.aws.credentials.secretKey=key
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/picpay-notification-email-queue
spring.cloud.aws.ses.endpoint=http://localhost:4566

spring.cloud.aws.sqs.endpoint.sms=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/picpay-notification-sms-queue

spring.cloud.aws.ses.email=from@example.com

spring.cloud.aws.sns.endpoint.http=http://localhost:4566

spring.cloud.aws.sns.endpoint=arn:aws:sns:us-east-1:000000000000:notification-sms-topic
